#!/usr/bin/perl
     
# les noms dans le tableau sont ceux des commentaires a coté des defines. Si vous les changer pensez a changer la valeur dans le .h
$total = 0;
open(FILE,"<./INC/syntax_tree.h") or die "POTATOES !";
print "char *node_name[] = {";
while (<FILE>) {
	chomp $_;
     	if($_ =~  m/#define\s+AT_[A-Z_]*\s+[0-9]+\s*\/\*\s*([a-zA-Z ]*?)\s*\*\//) {
	    print "\"$1\", ";
	    $total++;
	}
}
print "\b\b};\n";
print "Total de define : $total\n";
close (FILE);


