#!/bin/bash
# REYNAUD Nicolas, ABHAMON Ronan, BIGARD Florian
# vendredi 29 novembre 2013, 19:05:03 (UTC+0100)

# Dependance : VALGRIND
# Compile chaque programme du dossier BIN/examples avec valgrind
# Et affiche simplement les lignes retournée par valgrind qui indique le nombre de bytes allouées / free
# Ainsi que le résumé des erreurs 

if [ ! -e "./BIN/prog" ]; then 
	echo "Error : prog not found"
	exit -1;
fi

valgrind --version >/dev/null 2>&1 || { echo "Warning : Need Valgrind"; exit -1; }

for i in $(find "./SRC/" -type f ! -path "*/marche_pas/*"); do
    echo -e "Dans $i :\t"
    grep -o -E "fprintf\([ ]*stderr[ ]*,[ ]*\".*\"" $i | sed -e "s/fprintf([ ]*stderr[ ]*,[ ]*//g" -e "s/\"//" -e "s/\"$//g" -e "s/\n/\n/g"
    echo -e "\n"
    sleep 1
done 
