#!/bin/bash
# REYNAUD NICOLAS
# vendredi 29 novembre 2013, 19:05:03 (UTC+0100)


# Dependance : VALGRIND
# Compile chaque programme du dossier BIN/examples avec valgrind
# Et affiche simplement les lignes retournée par valgrind qui indique le nombre de bytes allouées / free
# Ainsi que le résumé des erreurs 

function sub() {
    echo -e "\nValgrind results for $1:"

    test=$(valgrind ./BIN/prog -c $1  2>&1)
    echo $test | sed -e "s/.*\(total heap usage:.*allocated\).*\(ERROR SUMMARY:.*\).*/\1\n\2/g"
}

valgrind --version >/dev/null 2>&1 || { echo "Warning : Need Valgrind"; exit -1; }

for i in $(find "./BIN/examples" -type f ! -path "*/marche_pas/*"); do
    sub "$i"
    sleep 1
done 
